# 配置服务端口
server:
  port: 7001

# 配置eureka相关
eureka:
  instance:
    hostname: localhost # eureka实例的名字
  client:
    register-with-eureka: false # 这个选项是“是否把自己注册到eureka服务端”，由于它自己就是服务端，选false
    fetch-registry: false # 是否从注册中心拉取服务，由于它自己就是服务端，选false
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 设置Eureka Server的可交互地址(注册地址)，
      #用于服务检索和服务注册，在多server下，就是其他节点的路径，单server节点的时候可以不配